Template.bugs.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('type', 'bug');
  });
});

Template.bugs.helpers({
  bugs: function() {
    return Docs.find({
      type: 'bug'
    });
  }
});

// ---
// generated by coffee-script 1.9.2