// Generated by CoffeeScript 1.10.0
(function() {
  this.selected_tags = new ReactiveArray([]);

  $.cloudinary.config({
    cloud_name: "facet"
  });

  FlowRouter.notFound = {
    action: function() {
      return BlazeLayout.render('layout', {
        main: 'not_found'
      });
    }
  };

  Template.body.events({
    'click .toggle_sidebar': function() {
      return $('.ui.sidebar').sidebar('toggle');
    }
  });

  Template.registerHelper('is_editing', function() {
    return Session.equals('editing_id', this._id);
  });

  Template.registerHelper('is_author', function() {
    return Meteor.userId() === this.author_id;
  });

  Template.registerHelper('can_edit', function() {
    return Meteor.userId() === this.author_id || Roles.userIsInRole(Meteor.userId(), 'admin');
  });

  Template.registerHelper('publish_when', function() {
    return moment(this.publish_date).fromNow();
  });

  Template.registerHelper('when', function() {
    return moment(this.timestamp).fromNow();
  });

  Template.registerHelper('is_dev', function() {
    return Meteor.isDevelopment;
  });

  Template.sidebar.onRendered(function() {
    return this.autorun((function(_this) {
      return function() {
        if (_this.subscriptionsReady()) {
          return Meteor.setTimeout(function() {
            return $('.context.example .ui.sidebar').sidebar({
              context: $('.context.example .bottom.segment'),
              dimPage: false,
              transition: 'push'
            }).sidebar('attach events', '.context.example .menu .toggle_sidebar.item');
          }, 500);
        }
      };
    })(this));
  });

}).call(this);
