Template.comments.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('comments', FlowRouter.getParam('doc_id'));
  });
});

Template.comments.helpers({
  comments: function() {
    return Docs.find({
      parent_id: FlowRouter.getParam('doc_id'),
      type: 'comment'
    });
  }
});

Template.comments.onRendered(function() {});

Template.comments.events({
  'keyup #new_comment': function(e, t) {
    var comment, new_comment_id;
    e.preventDefault();
    comment = $('#new_comment').val().trim();
    if (e.which === 13) {
      $('#new_comment').val('');
      new_comment_id = Docs.insert({
        type: 'comment',
        text: comment,
        parent_id: this._id
      });
      return Meteor.call('create_alert', 'comment', this._id, new_comment_id, function(err, res) {
        if (err) {
          return console.error(err);
        } else {

        }
      });
    }
  },
  'click .delete_comment': function() {
    if (confirm('delete comment?')) {
      return Docs.remove(this._id);
    }
  }
});

// ---
// generated by coffee-script 1.9.2