
Template.doc_view.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('doc', FlowRouter.getParam('doc_id'));
  });
});

Template.doc_view.helpers({
  doc: function() {
    return Docs.findOne(FlowRouter.getParam('doc_id'));
  },
  type_view: function() {
    return this.type + "_view";
  }
});


Template.doc_edit.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('doc', FlowRouter.getParam('doc_id'));
  });
});

Template.doc_edit.helpers({
  doc: function() {
    return Docs.findOne(FlowRouter.getParam('doc_id'));
  },
  type_edit: function() {
    return this.type + "_edit";
  }
});

// ---
// generated by coffee-script 1.9.2