import '/imports/ui/client/nav.jade'
import '/imports/ui/client/nav.js'
import '/imports/startup/client/routes.js'
import '/imports/startup/client/client.js'
import '/imports/ui/client/fields.jade'
import '/imports/ui/client/fields.js'
import '/imports/ui/client/actions.jade'
import '/imports/ui/client/actions.js'

import '/imports/ui/client/customers.jade'
import '/imports/ui/client/customers.js'
import '/imports/ui/client/ev.jade'
import '/imports/ui/client/ev.js'
import '/imports/ui/client/office.jade'
import '/imports/ui/client/office.js'
import '/imports/ui/client/incidents.jade'
import '/imports/ui/client/incidents.js'

import '/imports/ui/client/accounts/user_view.jade'
import '/imports/ui/client/accounts/user_view.js'

import '/imports/ui/client/accounts/user_edit.jade'
import '/imports/ui/client/accounts/user_edit.js'

import '/imports/ui/client/accounts/accounts.jade'
import '/imports/ui/client/accounts/accounts.js'
import '/imports/ui/client/accounts/account.jade'
import '/imports/ui/client/accounts/account.js'
import '/imports/ui/client/dashboard.jade'
import '/imports/ui/client/dashboard.js'
import '/imports/ui/client/blocks.jade'
import '/imports/ui/client/styles.css'
import '/imports/ui/client/footer.jade'
import '/imports/ui/client/client.jade'
