Template.roles.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('doc', FlowRouter.getParam('doc_id'));
  });
});

Template.roles.helpers;

FlowRouter.route('/roles', {
  action: function() {
    return BlazeLayout.render('layout', {
      main: 'roles'
    });
  }
});

Template.roles.onCreated(function() {
  return this.autorun((function(_this) {
    return function() {
      return Meteor.subscribe('docs', [], 'role');
    };
  })(this));
});

Template.roles.helpers({
  roles: function() {
    return Docs.find({
      type: 'role'
    });
  }
});

Template.role_card.onCreated(function() {});

Template.role_card.helpers;

Template.role_edit.events({
  'click #delete': function() {
    var template;
    template = Template.currentData();
    return swal({
      title: 'Delete role?',
      type: 'error',
      animation: false,
      showCancelButton: true,
      closeOnConfirm: true,
      cancelButtonText: 'Cancel',
      confirmButtonText: 'Delete',
      confirmButtonColor: '#da5347'
    }, (function(_this) {
      return function() {
        var doc;
        doc = Docs.findOne(FlowRouter.getParam('doc_id'));
        return Docs.remove(doc._id, function() {
          return FlowRouter.go("/roles");
        });
      };
    })(this));
  }
});

// ---
// generated by coffee-script 1.9.2