Template.rules.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('doc', FlowRouter.getParam('doc_id'));
  });
});

Template.rules.helpers;

FlowRouter.route('/rules', {
  action: function() {
    return BlazeLayout.render('layout', {
      main: 'rules'
    });
  }
});

Template.rules.onCreated(function() {
  return this.autorun((function(_this) {
    return function() {
      return Meteor.subscribe('docs', [], 'rule');
    };
  })(this));
});

Template.rules.helpers({
  rules: function() {
    return Docs.find({
      type: 'rule'
    });
  }
});

Template.rule_card.onCreated(function() {});

Template.rule_card.helpers;

Template.rule_edit.events({
  'click #delete': function() {
    var template;
    template = Template.currentData();
    return swal({
      title: 'Delete rule?',
      type: 'error',
      animation: false,
      showCancelButton: true,
      closeOnConfirm: true,
      cancelButtonText: 'Cancel',
      confirmButtonText: 'Delete',
      confirmButtonColor: '#da5347'
    }, (function(_this) {
      return function() {
        var doc;
        doc = Docs.findOne(FlowRouter.getParam('doc_id'));
        return Docs.remove(doc._id, function() {
          return FlowRouter.go("/rules");
        });
      };
    })(this));
  }
});

// ---
// generated by coffee-script 1.9.2