Meteor.startup(function() {
  Meteor.Mailgun.config({
    username: 'portalmailer@sandbox97641e5041e64bfd943374748157462b.mailgun.org',
    password: 'portalmailer'
  });
});

Meteor.methods({
  sendEmail: function(mail_fields) {
    console.log('about to send email...');
    console.log(mail_fields);
    this.unblock();
    if (Meteor.isProduction) {
      Meteor.Mailgun.send({
        to: mail_fields.to,
        from: mail_fields.from,
        subject: mail_fields.subject,
        text: mail_fields.text,
        html: mail_fields.html
      });
      console.log('email sent from prod');
    }
    if (Meteor.isDevelopment) {
      console.log('email sending from dev');
      Docs.insert({
        type: 'message',
        mail_fields: mail_fields
      });
    } else {
      console.log('not prod or dev');
    }
  },
  email_about_escalation: function(incident_id) {
    var customer, escalation_franchisee_value, escalation_primary_contact_value, escalation_secondary_contact_value, franchisee, incident, mail_fields, office_doc;
    incident = Docs.findOne(incident_id);
    customer = Docs.findOne({
      "ev.ID": incident.customer_jpid,
      type: 'customer'
    });
    franchisee = Docs.findOne({
      "ev.FRANCHISEE": customer.ev.FRANCHISEE,
      type: 'franchisee'
    });
    console.log('franchisee', franchisee);
    office_doc = Docs.findOne({
      "ev.MASTER_LICENSEE": incident.incident_office_name,
      type: 'office'
    });
    escalation_primary_contact_value = office_doc["escalation_" + incident.level + "_primary_contact"];
    escalation_secondary_contact_value = office_doc["escalation_" + incident.level + "_secondary_contact"];
    escalation_franchisee_value = office_doc["escalation_" + incident.level + "_contact_franchisee"];
    console.log(escalation_franchisee_value);
    console.log("escalation_" + incident.level + "_secondary_contact");
    console.log(escalation_primary_contact_value);
    console.log(escalation_secondary_contact_value);
    mail_fields = {
      to: ["richard@janhub.com <richard@janhub.com>", "zack@janhub.com <zack@janhub.com>", "Nicholas.Rose@premiumfranchisebrands.com <Nicholas.Rose@premiumfranchisebrands.com>", "nick.bhagat@premiumfranchisebrands.com <nick.bhagat@premiumfranchisebrands.com>"],
      from: "Jan-Pro Customer Portal <portal@jan-pro.com>",
      subject: "Incident from " + incident.customer_name + " has been escalated to " + incident.level + ".",
      text: '',
      html: "<h4>Incident from " + incident.customer_name + " escalated to " + incident.level + ".</h4> <h5>Type: " + incident.incident_type + "</h5> <h5>Details: " + incident.incident_details + "</h5> <h5>Office: " + incident.incident_office_name + "</h5> <h5>Status: " + incident.status + "</h5> <h5>Service Date: " + incident.service_date + "</h5> <h4>This will notify</h4> <h5>Primary Office Contact: " + escalation_primary_contact_value + "</h5> <h5>Secondary Office Contact: " + escalation_secondary_contact_value + "</h5> <h5>Franchisee: " + escalation_franchisee_value + ", " + franchisee.ev.FRANCHISEE + " at " + franchisee.ev.FRANCH_EMAIL + "</h5>"
    };
    Meteor.call('create_event', incident_id, 'emailed_primary_contact', escalation_primary_contact_value + " has been emailed as the primary contact for escalation to level " + incident.level + ".");
    Meteor.call('create_event', incident_id, 'emailed_secondary_contact', escalation_secondary_contact_value + " has been emailed as the secondary contact for escalation to level " + incident.level + ".");
    if (escalation_franchisee_value) {
      Meteor.call('create_event', incident_id, 'emailed_franchisee_contact', "Franchisee " + franchisee.ev.FRANCHISEE + " has been emailed for escalation to level " + incident.level + ".");
    }
    return Meteor.call('sendEmail', mail_fields);
  }
});

// ---
// generated by coffee-script 1.9.2