Meteor.users.allow({
  update: function(userId, doc, fields, modifier) {
    return true
  }
})

Cloudinary.config({
  cloud_name: 'facet',
  api_key: Meteor.settings.cloudinary_key,
  api_secret: Meteor.settings.cloudinary_secret
})

SyncedCron.config({
  log: true,
  logger: null,
  collectionName: 'cron_history',
  utc: false,
  collectionTTL: 17280
})

SyncedCron.add({
  name: 'Update incident escalations',
  schedule: function(parser) {
    return parser.text('every 1 hour')
  },
  job: function() {
    return Meteor.call('update_escalation_statuses', function(err, res) {
      if (err) {
        return console.log(err)
      }
    })
  }
})

Docs.allow({
  insert: function(user_id, doc) {
    return user_id
  },
  update: function(user_id, doc) {
    return user_id
  },
  remove: function(user_id, doc) {
    return user_id
  }
})

// ---
// generated by coffee-script 1.9.2