
Template.add_user.onCreated(function() {});

Template.add_user.helpers({
  unassigned_roles: function() {
    var role_list;
    role_list = ['admin', 'office', 'customer'];
    return _.difference(role_list, this.roles);
  }
});

Template.add_user.events({
  'click #add_person': function() {
    var email, first_name, last_name, username;
    username = $('#username').val().trim();
    first_name = $('#first_name').val().trim();
    last_name = $('#last_name').val().trim();
    email = $('#email').val().trim();
    return Meteor.call('create_user', username, first_name, last_name, email, function(err, new_id) {
      return FlowRouter.go("/user/" + username);
    });
  }
});

// ---
// generated by coffee-script 1.9.2