FlowRouter.route('/admin', {
  action: function() {
    return BlazeLayout.render('layout', {
      main: 'admin'
    });
  }
});

FlowRouter.route('/bugs', {
  action: function() {
    return BlazeLayout.render('layout', {
      main: 'bugs'
    });
  }
});

Template.bugs.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('type', 'bug');
  });
});

Template.bugs.helpers({
  bugs: function() {
    return Docs.find({
      type: 'bug'
    });
  }
});

// ---
// generated by coffee-script 1.9.2