Template.user_edit.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('user_profile', FlowRouter.getParam('user_id'));
  });
});

Template.user_edit.helpers({
  user: function() {
    return Meteor.users.findOne(FlowRouter.getParam('user_id'));
  }
});

Template.user_edit.events({
  'keydown #input_image_id': function(e, t) {
    var image_id, user_id;
    if (e.which === 13) {
      user_id = FlowRouter.getParam('user_id');
      image_id = $('#input_image_id').val().toLowerCase().trim();
      if (image_id.length > 0) {
        Meteor.users.update(user_id, {
          $set: {
            image_id: image_id
          }
        });
        return $('#input_image_id').val('');
      }
    }
  },
  "change input[type='file']": function(e) {
    var files;
    files = e.currentTarget.files;
    return Cloudinary.upload(files[0], function(err, res) {
      if (err) {
        console.error('Error uploading', err);
      } else {
        Meteor.users.update(FlowRouter.getParam('user_id'), {
          $set: {
            "profile.image_id": res.public_id
          }
        });
      }
    });
  },
  'click #remove_photo': function() {
    return swal({
      title: "Remove Profile Photo?",
      type: 'info',
      animation: false,
      showCancelButton: true,
      closeOnConfirm: true,
      cancelButtonText: 'Cancel',
      confirmButtonText: 'Remove',
      confirmButtonColor: '#da5347'
    }, (function(_this) {
      return function() {
        return Meteor.users.update(FlowRouter.getParam('user_id'), {
          $unset: {
            "profile.image_id": 1
          }
        });
      };
    })(this));
  }
});

// ---
// generated by coffee-script 1.9.2