FlowRouter.route('/user/:username', {
  action: function(params) {
    return BlazeLayout.render('layout', {
      main: 'user_view'
    });
  }
});

Template.user_view.onCreated(function() {
  return this.autorun(function() {
    return Meteor.subscribe('user', FlowRouter.getParam('username'));
  });
});

Template.user_view.helpers({
  user: function() {
    return Meteor.users.findOne({
      username: FlowRouter.getParam('username')
    });
  }
});

Template.user_view.events;

Template.users.events({
  'click .sync_ev_users': function() {
    return Meteor.call('sync_ev_users', function(err, res) {
      if (err) {
        return console.error(err);
      }
    });
  }
});

Template.users.helpers({
  selector: function() {
    return {
      type: "user"
    };
  }
});

Template.user_view.events({
  'click .get_user_info': function() {
    return Meteor.call('get_user_info', FlowRouter.getParam('username'), function(err, res) {
      if (err) {
        return Bert.alert("" + err.reason, 'danger', 'growl-top-right');
      }
    });
  }
});

// ---
// generated by coffee-script 1.9.2